name: Cross-Compile

on:
  push:
    branches:
      - main # or your default branch
  pull_request:
    branches:
      - main # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.1' # specify Go version

      - name: Create Build Directory
        run: mkdir -p build

      - name: Cross-Compile for Windows, macOS, and Linux
        run: |
          env GOOS=windows GOARCH=amd64 go build -o ./build/cloud-init-decoder-windows-amd64.exe
          env GOOS=darwin GOARCH=amd64 go build -o ./build/cloud-init-decoder-darwin-amd64
          env GOOS=linux GOARCH=amd64 go build -o ./build/cloud-init-decoder-linux-amd64

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: compiled-binaries
          path: ./build/
